#
# Put user-defined variables here
#

PLUGIN_NAME=ExampleQL
PLUGIN_VERSION=0000.00.01
PLUGIN_BUILD=0
BUNDLE_DOMAIN=com.example
#
# Supported UTI types(use space to separate each one)
# Do NOT use any quote character
# NOTE: use mdls(1) to fetch kMDItemContentType info
#
# .example dynamic UTI
#
PLUGIN_SUPPORTED_UTI=dyn.ah62d4rv4ge80n8dbrz2g23k

